import { useEffect, useRef, useState } from 'react';
import { Stage } from 'react-konva';
import { useCanvasStore } from '@/stores/canvasStore';
import { useProjectStore } from '@/stores/projectStore';
import { CanvasMode } from '@/types/database';
import { GridLayer } from './layers/GridLayer';
import { WallOutlineLayer } from './layers/WallOutlineLayer';
import { ZonesLayer } from './layers/ZonesLayer';
import { SkuPlacementLayer } from './layers/SkuPlacementLayer';
import { ValidationOverlayLayer } from './layers/ValidationOverlayLayer';
import { LightingLayer } from './layers/LightingLayer';
import { FurnitureLayer } from './layers/FurnitureLayer';
import { TrimLayer } from './layers/TrimLayer';
import { SelectionLayer } from './layers/SelectionLayer';
import { MeasurementsLayer } from './layers/MeasurementsLayer';
import { ZoneDimensionsLayer } from './layers/ZoneDimensionsLayer';
import { SnapGuidesLayer } from './layers/SnapGuidesLayer';
import { useCanvasViewport } from './interactions/useCanvasViewport';
import { useKeyboardShortcuts } from './interactions/useKeyboardShortcuts';
import { useMarqueeSelect } from './interactions/useMarqueeSelect';
import { useHistory } from './history/useHistory';
import { resetHistory } from './history/useHistory';
import { screenToCanvas } from '@/lib/coordinates';

interface CanvasContainerProps {
  mode: CanvasMode;
}

/**
 * Main canvas wrapper component.
 * Sets up the Konva Stage with responsive sizing.
 * Handles zoom, pan, and marquee selection interactions.
 * Renders layers in correct z-order.
 *
 * Note: Zone creation has been removed (Rule 65). Panel frame zones are
 * system-generated by the wallConfigEngine and are read-only.
 */
export function CanvasContainer({ mode }: CanvasContainerProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [stageSize, setStageSize] = useState({ width: 800, height: 600 });

  const viewport = useCanvasStore((s) => s.viewport);
  const setMode = useCanvasStore((s) => s.setMode);
  const currentTemplate = useProjectStore((s) => s.currentTemplate);
  const measurements = useProjectStore((s) => s.measurements);
  const wallGeometry = useProjectStore((s) => s.wallGeometry);

  const {
    handleWheel,
    handleMouseDown,
    handleMouseMove,
    handleMouseUp,
    handleKeyDown,
    handleKeyUp,
    handleTouchStart,
    handleTouchMove,
    handleTouchEnd,
    fitToViewport,
  } = useCanvasViewport();

  const history = useHistory();

  const { handleKeyDown: handleShortcutKeyDown } = useKeyboardShortcuts({ history });

  const {
    handleMarqueeStart,
    handleMarqueeMove,
    handleMarqueeEnd,
  } = useMarqueeSelect();

  // Set mode when prop changes
  useEffect(() => {
    setMode(mode);
  }, [mode, setMode]);

  // Responsive sizing
  useEffect(() => {
    const handleResize = () => {
      if (containerRef.current) {
        const { width, height } = containerRef.current.getBoundingClientRect();
        setStageSize({ width, height });
      }
    };

    handleResize();
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Keyboard events for space+drag pan and shortcuts
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      handleKeyDown(e);
      handleShortcutKeyDown(e);
    };
    window.addEventListener('keydown', onKeyDown);
    window.addEventListener('keyup', handleKeyUp);
    return () => {
      window.removeEventListener('keydown', onKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    };
  }, [handleKeyDown, handleKeyUp, handleShortcutKeyDown]);

  // Fit to viewport on initial load and template change only (not on every resize)
  const hasInitialized = useRef(false);
  const lastTemplateId = useRef<string | null>(null);

  useEffect(() => {
    if (currentTemplate && stageSize.width > 0) {
      const templateChanged = lastTemplateId.current !== currentTemplate.template_id;
      if (!hasInitialized.current || templateChanged) {
        hasInitialized.current = true;
        lastTemplateId.current = currentTemplate.template_id;
        // Clear history when switching templates/projects
        if (templateChanged) {
          resetHistory();
        }
        fitToViewport(
          currentTemplate.wall_geometry.base_width_mm,
          currentTemplate.wall_geometry.base_height_mm,
          stageSize.width,
          stageSize.height,
        );
      }
    }
  }, [currentTemplate, stageSize, fitToViewport]);

  const wallWidth = currentTemplate?.wall_geometry.base_width_mm ?? 3000;
  const wallHeight = currentTemplate?.wall_geometry.base_height_mm ?? 2400;

  // Handle click on empty canvas area for marquee selection
  const handleStageMouseDown = (e: { evt: MouseEvent; target: { getStage: () => unknown } }) => {
    // Forward to pan handler
    handleMouseDown(e as { evt: MouseEvent });

    // Marquee selection on left click in designer mode on empty canvas
    if (
      mode === CanvasMode.DESIGNER &&
      e.evt.button === 0 &&
      e.target === e.target.getStage()
    ) {
      const point = screenToCanvas(
        { x: e.evt.offsetX - viewport.panX, y: e.evt.offsetY - viewport.panY },
        wallHeight,
        { zoom: viewport.zoom, panX: 0, panY: 0 },
      );
      handleMarqueeStart(point.x, point.y);
    }
  };

  const handleStageMouseMove = (e: { evt: MouseEvent }) => {
    handleMouseMove(e);
    const point = screenToCanvas(
      { x: e.evt.offsetX - viewport.panX, y: e.evt.offsetY - viewport.panY },
      wallHeight,
      { zoom: viewport.zoom, panX: 0, panY: 0 },
    );
    handleMarqueeMove(point.x, point.y);
  };

  const handleStageMouseUp = () => {
    handleMouseUp();
    handleMarqueeEnd();
  };

  return (
    <div
      ref={containerRef}
      className="canvas-container"
      style={{ width: '100%', height: '100%', overflow: 'hidden', position: 'relative' }}
      data-testid="canvas-container"
    >
      <Stage
        width={stageSize.width}
        height={stageSize.height}
        scaleX={viewport.zoom}
        scaleY={viewport.zoom}
        x={viewport.panX}
        y={viewport.panY}
        onWheel={handleWheel}
        onMouseDown={handleStageMouseDown}
        onMouseMove={handleStageMouseMove}
        onMouseUp={handleStageMouseUp}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
        data-testid="canvas-stage"
      >
        <GridLayer wallWidth={wallWidth} wallHeight={wallHeight} />
        <WallOutlineLayer
          wallWidth={wallWidth}
          wallHeight={wallHeight}
          wallGeometry={wallGeometry}
          segmentAWidth={measurements?.segment_a_width_mm ?? undefined}
          segmentBWidth={measurements?.segment_b_width_mm ?? undefined}
        />
        <ZonesLayer wallHeight={wallHeight} />
        <SkuPlacementLayer wallHeight={wallHeight} />
        <ValidationOverlayLayer wallHeight={wallHeight} />
        <LightingLayer wallHeight={wallHeight} />
        <FurnitureLayer wallHeight={wallHeight} />
        <TrimLayer wallHeight={wallHeight} />
        <MeasurementsLayer wallWidth={wallWidth} wallHeight={wallHeight} />
        <ZoneDimensionsLayer wallHeight={wallHeight} />
        <SnapGuidesLayer wallWidth={wallWidth} wallHeight={wallHeight} />
        <SelectionLayer wallHeight={wallHeight} />
      </Stage>
    </div>
  );
}
